# -*- coding: utf-8 -*-
"""cruzeiro do sul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kg7x0YQtD-l6v7Zu5uqTSJAaCUYP7DDV

# Visualização de dados

Projeto da disciplina
um dataset usando ao menos três técnicas estudadas na

O projeto da disciplina consiste em apresentar uma implementação, em Python, da visualização de informações presentes disciplina

Requisitos:
. O dataset deve trazer dados reais.

• As visualizações devem ser adequadas à natureza dos dados e todas devem ser relacionadas entre si, já que se referem a partes do mesmo dataset.

• Deve ser escolhida ao menos uma técnica (mínimo três) de cada uma das cinco unidades da disciplina.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

CovidInformation = pd.read_csv('./Covid19.csv')
CovidInformation['Date'] = pd.to_datetime(CovidInformation['Date'])
CovidInformation.head()

y = CovidInformation.groupby('State/UnionTerritory').ConfirmedIndianNational.sum().sort_values()

y.head()

plt.figure(figsize=(6,11))
plt.barh(y.index, y.values)
plt.show()

y = CovidInformation.groupby('State/UnionTerritory').Cured.sum().sort_values(ascending=False).head(5)
plt.figure(figsize=(23,6))
plt.bar(y.index, y.values)
plt.show()

local = CovidInformation.ConfirmedIndianNational.sum()
foreign = CovidInformation.ConfirmedForeignNational.sum()

plt.pie([local, foreign], labels=['Indianos', "Estrangeiros"])
plt.show()